name: Run Tests

on:
  pull_request:
    branches:
      - main
      - develop
  push:
    branches:
      - develop

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install JupyterLab
      run: |
        pip install jupyterlab

    - name: Build frontend
      run: |
        cd frontend
        npm install
        npm run build
        cd ..

    - name: Install build tools
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel build

    - name: Build package
      run: |
        python -m build

    - name: Install dependencies
      run: |
        pip install -v dist/*.whl || pip install -v dist/*.tar.gz

    - name: Install test dependencies
      run: |
        pip install asynctest tornado pytest pytest-asyncio jupyter

    - name: Run tests
      run: |
        pytest tests/
